DROP TABLE IF EXISTS hasla_studentow CASCADE;
DROP TABLE IF EXISTS studenci CASCADE;
DROP TABLE IF EXISTS hasla_pracownikow CASCADE;
DROP TABLE IF EXISTS pracownicy CASCADE;
DROP TABLE IF EXISTS oddzialy CASCADE;
DROP TABLE IF EXISTS kategorie CASCADE;
DROP TABLE IF EXISTS studenci_kierunki CASCADE;
DROP TABLE IF EXISTS ksiazki_autorzy CASCADE;
DROP TABLE IF EXISTS ksiazki_kategorie CASCADE;
DROP TABLE IF EXISTS autorzy CASCADE;
DROP TABLE IF EXISTS kierunki CASCADE;
DROP TABLE IF EXISTS kierunki_kategorie CASCADE;
DROP TABLE IF EXISTS ksiazki CASCADE;
DROP TABLE IF EXISTS wypozyczenia CASCADE;
DROP TABLE IF EXISTS zwroty CASCADE;
DROP TABLE IF EXISTS wydarzenia CASCADE;
DROP TABLE IF EXISTS kary CASCADE;
DROP TABLE IF EXISTS kary_studenci CASCADE;
DROP TABLE IF EXISTS etaty CASCADE;
/* celowo zostawiam to w 2PN, rozbijanie tego nie ma sensu */
CREATE TABLE oddzialy (
    nazwa VARCHAR(200) NOT NULL UNIQUE,
    adres VARCHAR(200) NOT NULL,
    id_oddzialu INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE kierunki (
    nazwa VARCHAR(100) NOT NULL,
    id_oddzialu INT,
    id_kierunku INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    UNIQUE(id_oddzialu, id_kierunku),
    FOREIGN KEY (id_oddzialu) REFERENCES oddzialy
);

CREATE TABLE studenci (
    imie VARCHAR(40) NOT NULL,
    nazwisko VARCHAR(40) NOT NULL,
    nazwa_uzytkownika VARCHAR(40) NOT NULL UNIQUE,
    id_studenta INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE studenci_kierunki (
    id_studenta INT NOT NULL,
    id_kierunku INT NOT NULL,
    "start" TIMESTAMP NOT NULL,
    koniec TIMESTAMP NOT NULL,
    CHECK("start" < koniec),
    UNIQUE(id_studenta, id_kierunku),
    FOREIGN KEY (id_kierunku) REFERENCES kierunki,
    FOREIGN KEY (id_studenta) REFERENCES studenci
);

CREATE TABLE etaty (
    nazwa_etatu VARCHAR(80) NOT NULL UNIQUE,
    id_etatu INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE pracownicy (
    imie VARCHAR(40) NOT NULL,
    nazwisko VARCHAR(40) NOT NULL,
    nazwa_uzytkownika VARCHAR(40) NOT NULL UNIQUE,
    id_etatu INT,
    email VARCHAR(100) UNIQUE,
    telefon VARCHAR(20) UNIQUE,
    id_oddzialu INT,
    id_pracownika INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CHECK (email IS NOT NULL OR telefon IS NOT NULL),
    FOREIGN KEY (id_oddzialu) REFERENCES oddzialy,
    FOREIGN KEY (id_etatu) REFERENCES etaty
);

CREATE TABLE hasla_studentow (
    id_studenta INT NOT NULL UNIQUE,
    haslo_hash_s VARCHAR(128) NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES studenci
);

CREATE TABLE hasla_pracownikow (
    id_pracownika INT NOT NULL UNIQUE,
    haslo_hash_p VARCHAR(128) NOT NULL,
    FOREIGN KEY (id_pracownika) REFERENCES pracownicy
);

CREATE TABLE kategorie (
    nazwa VARCHAR(100) NOT NULL UNIQUE,
    nadkategoria INT,
    id_kategorii INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CHECK(nadkategoria <> id_kategorii),
    FOREIGN KEY (nadkategoria) REFERENCES kategorie
);

CREATE TABLE autorzy (
    imie VARCHAR(40),
    nazwisko VARCHAR(40),
    data_urodzenia TIMESTAMP,
    notka_biograficzna VARCHAR(200),
    UNIQUE(imie, nazwisko, data_urodzenia),
    id_autora INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE kierunki_kategorie (
    id_kierunku INT NOT NULL,
    id_kategorii INT NOT NULL,
    UNIQUE(id_kierunku, id_kategorii),
    FOREIGN KEY (id_kierunku) REFERENCES kierunki,
    FOREIGN KEY (id_kategorii) REFERENCES kategorie
);

CREATE TABLE ksiazki (
    tytul VARCHAR(100) NOT NULL,
    liczba_stron INT,
    rok_wydania INT,
    id_oddzialu INT NOT NULL,
    wypozyczona BOOLEAN DEFAULT FAlSE,
    unikalny_token NUMERIC(13) NOT NULL,
    id_ksiazki INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CHECK(COALESCE(liczba_stron, 1) > 0),
    CHECK(COALESCE(rok_wydania, 0) >= 0),
    FOREIGN KEY (id_oddzialu) REFERENCES oddzialy
);

-- musi byc wyzwalacz na token zeby byl unique
CREATE TABLE ksiazki_kategorie (
    unikalny_token NUMERIC(13) NOT NULL,
    id_kategorii INT NOT NULL,
    UNIQUE(unikalny_token, id_kategorii),
    FOREIGN KEY (id_kategorii) REFERENCES kategorie
);

-- tu tez
CREATE TABLE ksiazki_autorzy (
    unikalny_token NUMERIC(13) NOT NULL,
    id_autora INt NOT NULL,
    UNIQUE(unikalny_token, id_autora),
    FOREIGN KEY (id_autora) REFERENCES autorzy
);

CREATE TABLE wypozyczenia (
    id_studenta INT NOT NULL,
    id_pracownika INT,
    id_ksiazki INT NOT NULL,
    data_wypozyczenia TIMESTAMP,
    termin_oddania TIMESTAMP,
    id_wypozyczenia INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CHECK (data_wypozyczenia < termin_oddania),
    FOREIGN KEY (id_studenta) REFERENCES studenci,
    FOREIGN KEY (id_ksiazki) REFERENCES ksiazki
);

/* tu nie ma redundancji bo mozna zwracac do innych oddziałow */
CREATE TABLE zwroty (
    id_wypozyczenia INT UNIQUE NOT NULL,
    id_oddzialu INT NOT NULL,
    id_pracownika INT NOT NULL,
    data_zwrotu TIMESTAMP NOT NULL,
    id_zwrotu INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (id_wypozyczenia) REFERENCES wypozyczenia,
    FOREIGN KEY (id_oddzialu) REFERENCES oddzialy,
    FOREIGN KEY (id_pracownika) REFERENCES pracownicy
);

/* celowo mogą być NULLE */
CREATE TABLE wydarzenia (
    nazwa VARCHAR(200) NOT NULL,
    "data" TIMESTAMP,
    godzina TIME,
    opis VARCHAR(400),
    id_oddzialu INT,
    id_wydarzenia INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (id_oddzialu) REFERENCES oddzialy
);

/* kary bedziemy liczyc na podstawie ile dni po terminie oddano ksiazke, 
pewnie jakis wyzwalacz w zwrotach albo wypozyczeniach 
problem z typami kar, chce miec 2 rodzaje przetrzymanie, zniszczenie */ 
CREATE TABLE kary (
    nazwa_kary VARCHAR(40) NOT NULL,
    id_typu_kary INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CHECK(nazwa_kary = ANY (ARRAY['przetrzymanie', 'zniszczenie']))    
);

/* mozliwe kilka kar do 1 zwrotu */
CREATE TABLE kary_studenci (
    typ_kary INT NOT NULL,
    id_studenta INT NOT NULL,
    wysokosc_kary NUMERIC(5,2) NOT NULL,
    id_kary INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (id_studenta) REFERENCES studenci,
    FOREIGN KEY (typ_kary) REFERENCES kary
);



-----------------------------------------------------------------------------------------------------------



-- wydarzenia - nic szczegolnego sie nie dzieje, wystarcza ograniczenia strukturalne bez wyzwalaczy
-- funkcja typu utility usun przestarzale
create or replace function usun_stare_wydarzenia() returns void as
$$
declare 
    r record;
begin
    delete from wydarzenia where coalesce(data, now()) + interval '30 days' < now();
end;
$$
language plpgsql;

-- oddzialy, update i insert oddzialow nic szczegolnego pozwalamy to robic, ograniczenia strukturalne wystarczaja
-- przy delete robi sie ciekawiej, bo nie mozna usunac oddzialu w ktorym sa ksiazki, trzeba je przeniesc do np.
-- tego ktory ma najmniej ksiazek
create or replace function usun_oddzial() returns trigger as
$$
declare
    r record;
    id_kierunku_dousun int;
    id_migracji int;
begin
    id_migracji := (select id_oddzialu from ksiazki where id_oddzialu <> old.id_oddzialu group by id_oddzialu order by count(*) asc limit 1);
    update ksiazki set id_oddzialu = id_migracji where id_oddzialu = old.id_oddzialu;
    update pracownicy set id_oddzialu = null where id_oddzialu = old.id_oddzialu;
    update zwroty set id_oddzialu = id_migracji where id_oddzialu = old.id_oddzialu;
    for id_kierunku_dousun in (select id_kierunku from kierunki where id_oddzialu = old.id_oddzialu) loop
        delete from kierunki_kategorie where id_kierunku = id_kierunku_dousun;
        delete from studenci_kierunki where id_kierunku = id_kierunku_dousun;
        delete from kierunki where id_kierunku = id_kierunku_dousun;
    end loop;
    -- dopiero teraz mozna usunac oddzial, moze sie zdarzyc ze student zostanie bez kierunku, ale kto usuwa oddzial z dnia na dzien :}
    return old;
end;
$$
language plpgsql;
create trigger usun_oddzial before delete on oddzialy
    for each row execute procedure usun_oddzial();

-- kierunki, mozna modyfikowac, dodawac, nie ma wiekszej filozofii, oczywiscie ograniczenia strukturalne nie pozwalaja modyfikowac id
-- prawie wszedzie - wyjatek tokeny
-- usuwanie tez proste, moze sie zdarzyc ze student nie bedzie mial kierunku, ale ponownie, to nie jest problem bazy dancyh tylko zarzadcy uczelni
create or replace function usun_kierunek() returns trigger as
$$
begin
    delete from kierunki_kategorie where id_kierunku = old.id_kierunku;
    delete from studenci_kierunki where id_kierunku = old.id_kierunku;
    return old;
end;
$$
language plpgsql;
create trigger usun_kierunek before delete on kierunki
 for each row execute procedure usun_kierunek();

 -- kierunki_kategorie, studenci_kierunki, tu sie nic nie dzieje, wszytsko zalatwiaja klucze obce, nawet delete bez problemow

 -- usuwanie hasel, nie moge go zabronic, ale tu powstaje blokada

 -- usuwanie pracownika, wymyslilem sobie, zeby zostawic cala historie wypozyczen i zwrotow, problem pojawia sie gdy 
 -- chce usunac oddzial - (rozwiazane), chece usunac pracownika - jedyny sensowny pomysl na jaki wpadlem to dodanie 
 -- abstrakcyjnego pracownika 
create or replace function usun_pracownika_t() returns trigger as
$$
begin
    if old.nazwa_uzytkownika = 'postgres' then
        raise exception 'nie mozna usunac postgresa';
    end if;
    update wypozyczenia set id_pracownika = null where id_pracownika = old.id_pracownika;
    update zwroty set id_pracownika = (select id_pracownika from pracownicy where nazwa_uzytkownika = 'postgres' limit 1) where id_pracownika = old.id_pracownika;
    delete from hasla_pracownikow where id_pracownika = old.id_pracownika;
    return old; 
end;
$$
language plpgsql;
create trigger usun_pracownika_t before delete on pracownicy
    for each row execute procedure usun_pracownika_t();

create rule niezmieniajpostgresa as on update to pracownicy
    where old.nazwa_uzytkownika = 'postgres'
    do instead nothing;

-- z usuwaniem studentow i ich hasel analogicznie
create or replace function usun_studenta_t() returns trigger as
$$
declare
    i int;
    czymoznausun boolean := true;
begin
    for i in (select id_ksiazki from wypozyczenia where id_studenta = old.id_studenta) loop
        if (select wypozyczona from ksiazki where id_ksiazki = i limit 1) = true then
            czymoznausun := false;
            exit;
        end if;
    end loop;
    if czymoznausun = false then
        raise exception 'student ma wypozyczona ksiazke';
        return null;
    end if;
    czymoznausun := true;
    if (select id_kary from kary_studenci where id_studenta = old.id_studenta) is not null then
        czymoznausun := false;
    end if;
    
    if czymoznausun = false then
        raise exception 'student ma kare';
        return null;
    end if;
    delete from studenci_kierunki where id_studenta = old.id_studenta;
    delete from hasla_studentow where id_studenta = old.id_studenta;
    return old;
end;
$$
language plpgsql;
create trigger usun_studenta_t before delete on studenci
    for each row execute procedure usun_studenta_t();

-- nazwa_uzytkownika w studentach i pracownikach są unikalne i nie musze sie martwic o ich spojnosc przy 
-- insert i update, problem bo 2 tabele sa rozlaczne dlatego trigger
create or replace function unikalna_nazwa_uzytkownika() returns trigger as
$$
begin
    if not (new.nazwa_uzytkownika in (select nazwa_uzytkownika from studenci) 
        or new.nazwa_uzytkownika in (select nazwa_uzytkownika from pracownicy)) then
            return new;
    end if;
    raise exception 'nazwa uzytkownika nie jest unikalna';
end;
$$
language plpgsql;
create trigger unikalna_nazwa_uzytkownika_st before insert or update on studenci
    for each row execute procedure unikalna_nazwa_uzytkownika();
create trigger unikalna_nazwa_uzytkownika_pr before insert or update on pracownicy
    for each row execute procedure unikalna_nazwa_uzytkownika();

-- indexy na tokenach 
create index unikalny_token_ind_k on ksiazki (unikalny_token);
create index unikalny_token_ind_kk on ksiazki_kategorie (unikalny_token);
create index unikalny_token_ind_ka on ksiazki_autorzy (unikalny_token);
-- inne indexy sa juz utworzone przez klucze glowne
create index studenci_ind_wyp on wypozyczenia (id_studenta);
create index ksiazki_ind_wyp on wypozyczenia (id_ksiazki);



-- wszedzie powinna byc zabroniona zmiana id, ale korzystam z wlasnosci foreign key, ktory domyslnie 
-- zabrania modyfikacji dlatego nie ma triggerow, jedyny wyjatek tokeny ksiazek bo nie jest kluczem obcym
create or replace function sprawdz_unikalny_token() returns trigger as 
$$
declare 
    r NUMERIC(13);
begin
    r := (select unikalny_token from ksiazki where tytul = new.tytul and liczba_stron = new.liczba_stron and rok_wydania = new.rok_wydania limit 1);
    if r is null then
        return new;
    else
        if r <> new.unikalny_token then
            raise exception 'podano niewlasciwy token';
        end if;
        return new;
    end if;
end;
$$
language plpgsql;
create trigger sprawdz_unikalny_token before insert or update on ksiazki
    for each row execute procedure sprawdz_unikalny_token();

create or replace function usun_ksiazke() returns trigger as
$$
begin
    if (select wypozyczona from ksiazki where id_ksiazki = old.id_ksiazki) = true then
        raise exception 'nie mozna usunac wypozyczonej ksiazki';
    end if;
    if (select count(*) from ksiazki where unikalny_token = old.unikalny_token) = 1 then 
        delete from ksiazki_autorzy where unikalny_token = old.unikalny_token;
        delete from ksiazki_kategorie where unikalny_token = old.unikalny_token;
    end if;
    return old;
end;
$$
language plpgsql;
create trigger usun_ksiazke before delete on ksiazki
    for each row execute procedure usun_ksiazke();

create rule zabron_update_ka as on update to ksiazki_autorzy
    do instead nothing;

create rule zabron_update_kk as on update to ksiazki_kategorie
    do instead nothing;

-- ksiazki wydane pozniej niz urodzenie autorow
create or replace function dodaj_ksiazke_wiele_do_wielu_ka() returns trigger as
$$
begin 
    if (new.unikalny_token in (select distinct unikalny_token from ksiazki)) then
        if to_timestamp((select rok_wydania from ksiazki where unikalny_token = new.unikalny_token limit 1)) <= (select data_urodzenia from autorzy where id_autora = new.id_autora) then 
            delete from ksiazki where unikalny_token = new.unikalny_token;
            raise exception 'bledna data wydania, usunieto ksiazke';
        else 
            return new;
        end if; 
    else 
        raise exception 'bledny token';
    end if;
end;
$$
language plpgsql;
create trigger dodaj_ksiazke_wiele_do_wielu_ka before insert on ksiazki_autorzy 
    for each row execute procedure dodaj_ksiazke_wiele_do_wielu_ka();

create or replace function dodaj_ksiazke_wiele_do_wielu_kk() returns trigger as
$$
begin
    if (new.unikalny_token in (select distinct unikalny_token from ksiazki)) then
        return new;
    else 
        raise exception 'bledny token';
    end if;
end;
$$
language plpgsql;
create trigger dodaj_ksiazke_wiele_do_wielu_kk before insert on ksiazki_kategorie
    for each row execute procedure dodaj_ksiazke_wiele_do_wielu_kk();

-- inserty, updaty, delete na autorach są bezpieczne przez strukture
create or replace function nieznany() returns trigger as
$$
begin
    if (new.imie = '' and new.nazwisko = '') or (new.imie is null and new.nazwisko is null) then
        new.imie := 'nieznany';
        new.nazwisko := 'nieznany';
        new.data_urodzenia := null;
    end if;
    return new;
end;
$$
language plpgsql;
create trigger nieznany before insert or update on autorzy
    for each row execute procedure nieznany();

-- wypozyczenia i zwroty
create or replace function wypozycz() returns trigger as 
$$
declare
    odd int;
begin 
    if (select count(*) from wypozyczenia w join ksiazki k on w.id_ksiazki = k.id_ksiazki where k.wypozyczona = true and w.id_studenta = new.id_studenta) >= 10 then
        raise exception 'nie mozna wypozyczyc wiecej niz 10 ksiazek';
    end if;
    if (select k.wypozyczona from ksiazki k where k.id_ksiazki = new.id_ksiazki) = true then
        raise exception 'ta ksiazka jest wypozyczona';
    end if;
    if (select imie from pracownicy p where p.id_pracownika = new.id_pracownika) is null then
        raise exception 'niepoprawny pracownik';
    end if;
    update ksiazki set wypozyczona = true where id_ksiazki = new.id_ksiazki;
    new.data_wypozyczenia := now();
    new.termin_oddania := now() + interval '14 days';
    return new;
end;
$$
language plpgsql;

create trigger wypozycz before insert on wypozyczenia
    for each row execute procedure wypozycz();

create or replace function usunwypozyczenie() returns trigger as 
$$
begin
    if (select id_zwrotu from zwroty where id_wydarzenia = old.id_wypozyczenia) is null then
        raise exception 'ta ksiazka jest wypozyczona';
        return null; 
    end if;
    return old;
end;
$$
language plpgsql;
create trigger usunwypozyczenie before delete on wypozyczenia
    for each row execute procedure usunwypozyczenie();

create rule niezmieniajwypozyczen as on update to wypozyczenia
    where old.id_studenta <> new.id_studenta or old.id_ksiazki <> new.id_ksiazki 
        or old.data_wypozyczenia <> new.data_wypozyczenia or old.termin_oddania <> new.termin_oddania
    do instead nothing; 

create or replace function dodajzwrot() returns trigger as 
$$
begin
    if new.data_zwrotu is null then
        new.data_zwrotu := now();
    end if;
    if new.data_zwrotu <= (select data_wypozyczenia from wypozyczenia where id_wypozyczenia = new.id_wypozyczenia) then
        raise exception 'cos nie tak z data oddania';
    end if;
    update ksiazki set wypozyczona = false where id_ksiazki = (select id_ksiazki from wypozyczenia where id_wypozyczenia = new.id_wypozyczenia);
    update ksiazki set id_oddzialu = new.id_oddzialu where id_ksiazki = (select id_ksiazki from wypozyczenia where id_wypozyczenia = new.id_wypozyczenia);
    if new.data_zwrotu > (select termin_oddania from wypozyczenia where id_wypozyczenia = new.id_wypozyczenia) then
        insert into kary_studenci values(1, (select id_studenta from wypozyczenia where id_wypozyczenia = new.id_wypozyczenia), 10.00);
    end if;
    return new;
end;
$$
language plpgsql;
create trigger dodajzwrot before insert on zwroty
    for each row execute procedure dodajzwrot();

create rule niezmieniajzwrotow as on update to zwroty
    where old.id_wypozyczenia <> new.id_wypozyczenia or old.data_zwrotu <> new.data_zwrotu 
    do instead nothing; 




-------------------------------------------------------------------------------------------------------------





COPY oddzialy (nazwa, adres) FROM stdin (Delimiter',');
Wydział Matematyki i Informatyki,ul. Profesora Stanisława Łojasiewicza 6
Wydział Zarządzania i Komunikacji Społecznej,ul. Profesora Stanisława Łojasiewicza 4
Wydział Fizyki Astronomii i Informatyki Stosowanej,ul. Profesora Stanisława Łojasiewicza 11
Wydział Chemii,ul. Gronostajowa 2
Wydział Biologii,ul. Gronostajowa 7
Wydział Filozoficzny,ul. Gołębia 24
\.

COPY wydarzenia (nazwa, data, godzina, opis, id_oddzialu) FROM stdin (Delimiter',');
Wielkie liczenie całek,\N,\N,Uczestnicy dostają pięć losowych całek. Sprawdź się,1
LAMBDA CALCULUS,\N,\N,Wstęp do rachunku lambda i całej dobroci na świecie,1
Koncert skrzypkowy,\N,\N,\N,3
Oglądanie gwiazd na dachu,\N,\N,\N,4
Bioszkielety,\N,\N,\N,5
Wspólne czytanie Joycea,\N,\N,\N,2
\.

COPY kierunki (nazwa, id_oddzialu) FROM stdin (Delimiter',');
TCS,1
Matematyka,1
Informatyka,1
Matematyka komputerowa,1
Finanse,2
Rachunkowość,2
Socjologia,2
Biznes,2
Fizyka,3
Informatyka stosowana,3
Geologia,3
Chemia organiczna,4
Chemia nieorganiczna,4
Biofizyka,5
Biotechnologia,5
Filozofia klasyczna,6
Filozofia współczesna,6
\.

COPY kategorie (nazwa, nadkategoria) FROM stdin (Delimiter',');
Matematyka,\N
Nauki ścisłe,\N
Informatyka,\N
Literatura piękna,\N
Chemia,2
Fizyka,2
Biologia,2
Anatomia człowieka,7
Systemy operacyjne,3
Historia,\N
Ekonamia,\N
Filozofia,4
Komedia,4
Oparte na faktach,4
\.

COPY kierunki_kategorie(id_kierunku, id_kategorii) FROM stdin (Delimiter',');
1,1
1,2
1,3
1,9
2,1
2,2
3,1
3,2
3,3
3,9
4,1
4,2
5,1
5,11
6,1
7,12
8,11
9,1
9,2
10,1
10,3
11,2
12,2
12,5
13,2
13,5
14,5
14,6
14,7
15,5
15,6
15,7
16,10
16,12
17,10
17,12
\.

COPY kary (nazwa_kary) FROM stdin (Delimiter',');
przetrzymanie
zniszczenie
\.

COPY etaty (nazwa_etatu) FROM stdin (Delimiter',');
Wielki mistrz biblioteki
Bibliotekarz wyższy
Bibliotekarz niższy
Asystent
Mol książkowy
Konserwator powierzchni internetowej
\.

COPY ksiazki (tytul, liczba_stron, rok_wydania, id_oddzialu, wypozyczona, unikalny_token) FROM stdin (Delimiter',');
Fundamentals of Wavelets,934,1951,5,FALSE,6729563152042
Data Smart,981,1998,5,FALSE,1014633866709
God Created the Integers,587,1997,2,FALSE,3166431008118
God Created the Integers,587,1997,5,FALSE,3166431008118
God Created the Integers,587,1997,5,FALSE,3166431008118
Superfreakonomics,851,1965,2,FALSE,3979388223397
Superfreakonomics,851,1965,1,FALSE,3979388223397
Superfreakonomics,851,1965,3,FALSE,3979388223397
Orientalism,186,1976,5,FALSE,6150458423795
Nature of Statistical Learning Theory,761,1955,3,FALSE,8751968732907
Nature of Statistical Learning Theory,761,1955,4,FALSE,8751968732907
Nature of Statistical Learning Theory,761,1955,1,FALSE,8751968732907
Integration of the Indian States,378,1994,5,FALSE,8410479003365
Integration of the Indian States,378,1994,3,FALSE,8410479003365
Integration of the Indian States,378,1994,1,FALSE,8410479003365
Drunkard's Walk,515,1966,5,FALSE,2070683790143
Drunkard's Walk,515,1966,5,FALSE,2070683790143
Image Processing & Mathematical Morphology,525,1977,3,FALSE,1503906609017
How to Think Like Sherlock Holmes,984,2016,1,FALSE,3310873923488
Data Scientists at Work,490,2003,2,FALSE,1573608583323
Data Scientists at Work,490,2003,2,FALSE,1573608583323
Slaughterhouse Five,771,1969,1,FALSE,7847063688177
Birth of a Theorem,323,2015,6,FALSE,3821770068792
Structure & Interpretation of Computer Programs,894,2014,3,FALSE,1103956323394
Structure & Interpretation of Computer Programs,894,2014,6,FALSE,1103956323394
Age of Wrath,913,1951,6,FALSE,4988817066876
Age of Wrath,913,1951,6,FALSE,4988817066876
Trial,581,1960,1,FALSE,2395927307726
Trial,581,1960,3,FALSE,2395927307726
Statistical Decision Theory',724,1983,3,FALSE,2445933217454
Statistical Decision Theory',724,1983,2,FALSE,2445933217454
Data Mining Handbook,866,1996,4,FALSE,9061117269737
Data Mining Handbook,866,1996,4,FALSE,9061117269737
Data Mining Handbook,866,1996,3,FALSE,9061117269737
New Machiavelli,772,1962,1,FALSE,3276109300072
New Machiavelli,772,1962,5,FALSE,3276109300072
Physics & Philosophy,391,2013,4,FALSE,5534886439718
Physics & Philosophy,391,2013,6,FALSE,5534886439718
Making Software,221,1971,6,FALSE,2715641095730
Making Software,221,1971,3,FALSE,2715641095730
Analysis,237,1978,3,FALSE,8194854910886
Machine Learning for Hackers,138,2019,5,FALSE,3337527420528
Machine Learning for Hackers,138,2019,6,FALSE,3337527420528
Signal and the Noise,870,1985,5,FALSE,9874444732043
Python for Data Analysis,844,2003,4,FALSE,8438583493043
Introduction to Algorithms,856,1974,1,FALSE,6666992569138
Introduction to Algorithms,856,1974,1,FALSE,6666992569138
Beautiful and the Damned,899,1991,2,FALSE,3703653195137
Outsider,288,1993,2,FALSE,2408086432268
Outsider,288,1993,5,FALSE,2408086432268
Outsider,288,1993,6,FALSE,2408086432268
Complete Sherlock Holmes,453,1970,2,FALSE,3864952503502
Complete Sherlock Holmes,453,1970,5,FALSE,3864952503502
Complete Sherlock Holmes,146,1979,4,FALSE,4950791696587
Complete Sherlock Holmes,146,1979,2,FALSE,4950791696587
Complete Sherlock Holmes,146,1979,2,FALSE,4950791696587
Wealth of Nations,841,1955,3,FALSE,4457692192175
Wealth of Nations,841,1955,1,FALSE,4457692192175
Wealth of Nations,841,1955,1,FALSE,4457692192175
Pillars of the Earth,89,1989,3,FALSE,7041157546116
Mein Kampf,979,1998,2,FALSE,1196036295926
Mein Kampf,979,1998,5,FALSE,1196036295926
Mein Kampf,979,1998,5,FALSE,1196036295926
Tao of Physics,148,1953,6,FALSE,4984702655237
Tao of Physics,148,1953,3,FALSE,4984702655237
Surely You're Joking Mr Feynman,721,2019,5,FALSE,4077470030548
Surely You're Joking Mr Feynman,721,2019,2,FALSE,4077470030548
Surely You're Joking Mr Feynman,721,2019,1,FALSE,4077470030548
Farewell to Arms,297,1962,2,FALSE,8890009561557
Farewell to Arms,297,1962,2,FALSE,8890009561557
Veteran,104,1976,2,FALSE,7312840521722
False Impressions,54,1999,4,FALSE,5670712431847
False Impressions,54,1999,2,FALSE,5670712431847
Last Lecture,845,1994,2,FALSE,3806803489735
Last Lecture,845,1994,4,FALSE,3806803489735
Last Lecture,845,1994,2,FALSE,3806803489735
Return of the Primitive,947,2001,2,FALSE,9529830388835
Jurassic Park,480,1982,3,FALSE,7591274432651
Jurassic Park,480,1982,2,FALSE,7591274432651
Russian Journal,505,1976,1,FALSE,8940985935341
Russian Journal,505,1976,6,FALSE,8940985935341
Russian Journal,505,1976,4,FALSE,8940985935341
Tales of Mystery and Imagination,223,1988,6,FALSE,3295708841378
Tales of Mystery and Imagination,223,1988,3,FALSE,3295708841378
Freakonomics,299,1963,6,FALSE,9519263308660
Freakonomics,299,1963,1,FALSE,9519263308660
Hidden Connections,59,1972,4,FALSE,1813594418598
Hidden Connections,59,1972,2,FALSE,1813594418598
Hidden Connections,59,1972,5,FALSE,1813594418598
Story of Philosophy,308,2012,6,FALSE,4769134534695
Asami Asami,702,2009,3,FALSE,6557719081108
Journal of a Novel,961,1989,5,FALSE,3318082805969
Journal of a Novel,961,1989,4,FALSE,3318082805969
Journal of a Novel,961,1989,2,FALSE,3318082805969
Once There Was a War,237,1959,3,FALSE,7756274497478
Once There Was a War,237,1959,5,FALSE,7756274497478
Once There Was a War,237,1959,5,FALSE,7756274497478
Moon is Down,878,1993,3,FALSE,6131558292251
Moon is Down,878,1993,2,FALSE,6131558292251
Moon is Down,878,1993,1,FALSE,6131558292251
Brethren,746,2001,4,FALSE,3445864921706
Brethren,746,2001,4,FALSE,3445864921706
In a Free State,323,1967,5,FALSE,4525160406226
In a Free State,323,1967,4,FALSE,4525160406226
Catch 22,478,1994,3,FALSE,4565543007532
Complete Mastermind,415,1964,5,FALSE,7572023417380
Complete Mastermind,415,1964,3,FALSE,7572023417380
Dylan on Dylan,459,1952,3,FALSE,6043519184697
Dylan on Dylan,459,1952,6,FALSE,6043519184697
Soft Computing & Intelligent Systems,564,2004,6,FALSE,6840320046576
Soft Computing & Intelligent Systems,564,2004,2,FALSE,6840320046576
Soft Computing & Intelligent Systems,564,2004,4,FALSE,6840320046576
Textbook of Economic Theory,256,2020,6,FALSE,6754683435055
Textbook of Economic Theory,256,2020,1,FALSE,6754683435055
Econometric Analysis,906,2021,1,FALSE,2935989317694
Econometric Analysis,906,2021,6,FALSE,2935989317694
Learning OpenCV,561,2013,5,FALSE,7178656973092
Learning OpenCV,561,2013,4,FALSE,7178656973092
Learning OpenCV,561,2013,2,FALSE,7178656973092
Data Structures Using C & C++,322,2001,5,FALSE,4489833524936
Computer Vision,178,1959,4,FALSE,4107897544048
Computer Vision,178,1959,1,FALSE,4107897544048
Computer Vision,178,1959,6,FALSE,4107897544048
Principles of Communication Systems,56,2015,2,FALSE,5025723308014
Principles of Communication Systems,56,2015,1,FALSE,5025723308014
Principles of Communication Systems,56,2015,1,FALSE,5025723308014
Let Us C,337,1981,3,FALSE,2940061686577
Let Us C,337,1981,5,FALSE,2940061686577
Amulet of Samarkand,398,1981,3,FALSE,5154540150755
Amulet of Samarkand,398,1981,2,FALSE,5154540150755
Crime and Punishment,80,2005,2,FALSE,3196057839502
Crime and Punishment,80,2005,2,FALSE,3196057839502
Crime and Punishment,80,2005,5,FALSE,3196057839502
Angels & Demons,611,1977,6,FALSE,7092094079047
Angels & Demons,611,1977,5,FALSE,7092094079047
Argumentative Indian,318,2018,4,FALSE,8271414721143
Argumentative Indian,318,2018,1,FALSE,8271414721143
Sea of Poppies,705,1994,3,FALSE,6895840887435
Idea of Justice,857,2001,1,FALSE,2104120929684
Idea of Justice,857,2001,2,FALSE,2104120929684
Idea of Justice,857,2001,2,FALSE,2104120929684
Raisin in the Sun,354,1957,5,FALSE,2868244317596
Raisin in the Sun,354,1957,6,FALSE,2868244317596
Raisin in the Sun,354,1957,3,FALSE,2868244317596
All the President's Men,173,1963,5,FALSE,3336350705716
All the President's Men,173,1963,1,FALSE,3336350705716
All the President's Men,173,1963,6,FALSE,3336350705716
Prisoner of Birth,266,2005,1,FALSE,2824954837500
Prisoner of Birth,266,2005,5,FALSE,2824954837500
Scoop!,671,2021,1,FALSE,1786737440113
Ahe Manohar Tari,743,1958,1,FALSE,8200019656134
Last Mughal,340,1977,2,FALSE,7779826332167
Last Mughal,340,1977,1,FALSE,7779826332167
Last Mughal,340,1977,4,FALSE,7779826332167
Social Choice & Welfare,895,2011,6,FALSE,8321473552475
Social Choice & Welfare,895,2011,5,FALSE,8321473552475
Radiowaril Bhashane & Shrutika,359,1983,5,FALSE,3425070305420
Gun Gayin Awadi,180,2002,6,FALSE,5180853337094
Aghal Paghal,911,2007,1,FALSE,1735550908152
Maqta-e-Ghalib,476,1983,3,FALSE,1001279279670
Maqta-e-Ghalib,476,1983,3,FALSE,1001279279670
Beyond Degrees,548,2002,1,FALSE,5714537331897
Manasa,363,2003,6,FALSE,5897507298928
Manasa,363,2003,6,FALSE,5897507298928
Manasa,363,2003,2,FALSE,5897507298928
India from Midnight to Milennium,598,1990,5,FALSE,8945761395204
India from Midnight to Milennium,598,1990,1,FALSE,8945761395204
World's Greatest Trials,662,1987,1,FALSE,3402496073178
Great Indian Novel,125,1958,1,FALSE,7485925923565
Great Indian Novel,125,1958,2,FALSE,7485925923565
O Jerusalem!,932,1958,5,FALSE,8416450607048
O Jerusalem!,932,1958,4,FALSE,8416450607048
O Jerusalem!,932,1958,5,FALSE,8416450607048
City of Joy,688,1959,3,FALSE,6170155389673
City of Joy,688,1959,1,FALSE,6170155389673
City of Joy,688,1959,2,FALSE,6170155389673
Freedom at Midnight,430,1979,4,FALSE,4187709059758
Winter of Our Discontent,337,2007,3,FALSE,3016871132439
Winter of Our Discontent,337,2007,6,FALSE,3016871132439
Winter of Our Discontent,337,2007,2,FALSE,3016871132439
On Education,409,1973,1,FALSE,1203924092495
Free Will,933,1991,2,FALSE,5050639084270
Bookless in Baghdad,821,1974,1,FALSE,7544691406925
Bookless in Baghdad,821,1974,6,FALSE,7544691406925
Case of the Lame Canary,923,2006,2,FALSE,3123529631678
Case of the Lame Canary,923,2006,4,FALSE,3123529631678
Case of the Lame Canary,923,2006,5,FALSE,3123529631678
Theory of Everything,78,1978,6,FALSE,4464398397212
Theory of Everything,78,1978,1,FALSE,4464398397212
New Markets & Other Essays,928,1960,2,FALSE,3637338181330
Electric Universe,517,1958,1,FALSE,1064149956681
Electric Universe,517,1958,2,FALSE,1064149956681
Electric Universe,517,1958,5,FALSE,1064149956681
Hunchback of Notre Dame,550,1953,2,FALSE,7585429115614
Burning Bright,970,2000,4,FALSE,6479758169529
Age of Discontuinity,655,1955,1,FALSE,7214443729247
Age of Discontuinity,655,1955,2,FALSE,7214443729247
Doctor in the Nude,579,1953,1,FALSE,9546616317438
Doctor in the Nude,579,1953,4,FALSE,9546616317438
Down and Out in Paris & London,671,1976,6,FALSE,6257874156783
Down and Out in Paris & London,671,1976,5,FALSE,6257874156783
Identity & Violence,900,1999,5,FALSE,4065255404829
Identity & Violence,900,1999,1,FALSE,4065255404829
Identity & Violence,900,1999,2,FALSE,4065255404829
Beyond the Three Seas,764,1973,2,FALSE,9488110719161
Beyond the Three Seas,764,1973,6,FALSE,9488110719161
Beyond the Three Seas,764,1973,6,FALSE,9488110719161
World's Greatest Short Stories,130,1979,5,FALSE,8465721830580
World's Greatest Short Stories,130,1979,2,FALSE,8465721830580
World's Greatest Short Stories,130,1979,4,FALSE,8465721830580
Talking Straight,342,1973,2,FALSE,3513097276126
Maugham's Collected Short Stories,257,1959,2,FALSE,2477763455615
Phantom of Manhattan,747,1996,1,FALSE,1574693943745
Phantom of Manhattan,747,1996,5,FALSE,1574693943745
Phantom of Manhattan,747,1996,1,FALSE,1574693943745
Ashenden of The British Agent,193,1954,6,FALSE,8605438025356
Zen & The Art of Motorcycle Maintenance,724,2020,3,FALSE,3127814260230
Zen & The Art of Motorcycle Maintenance,724,2020,6,FALSE,3127814260230
Zen & The Art of Motorcycle Maintenance,724,2020,6,FALSE,3127814260230
Great War for Civilization,662,1957,1,FALSE,6163804811943
We the Living,619,1998,2,FALSE,6494319505401
We the Living,619,1998,3,FALSE,6494319505401
Artist and the Mathematician,762,1963,3,FALSE,8038081819134
History of Western Philosophy,766,2000,4,FALSE,6347509939946
History of Western Philosophy,766,2000,6,FALSE,6347509939946
History of Western Philosophy,766,2000,5,FALSE,6347509939946
Selected Short Stories,656,2015,6,FALSE,6172217379259
Selected Short Stories,656,2015,1,FALSE,6172217379259
Selected Short Stories,656,2015,5,FALSE,6172217379259
Rationality & Freedom,155,1953,3,FALSE,8468296521342
Rationality & Freedom,155,1953,6,FALSE,8468296521342
Clash of Civilizations and Remaking of the World Order,508,1993,1,FALSE,1435023114521
Clash of Civilizations and Remaking of the World Order,508,1993,2,FALSE,1435023114521
Clash of Civilizations and Remaking of the World Order,508,1993,4,FALSE,1435023114521
Uncommon Wisdom,408,1957,4,FALSE,3362307658463
One,432,2002,4,FALSE,3864611194399
One,432,2002,6,FALSE,3864611194399
One,432,2002,5,FALSE,3864611194399
Karl Marx Biography,85,1972,5,FALSE,9573404173566
To Sir With Love,688,2014,4,FALSE,3186466186968
To Sir With Love,688,2014,4,FALSE,3186466186968
To Sir With Love,688,2014,3,FALSE,3186466186968
Half A Life,521,2019,2,FALSE,9266170429737
Half A Life,521,2019,6,FALSE,9266170429737
Half A Life,521,2019,5,FALSE,9266170429737
Discovery of India,731,1965,6,FALSE,8002913475297
Discovery of India,731,1965,5,FALSE,8002913475297
Apulki,342,1979,6,FALSE,5398600645438
Apulki,342,1979,6,FALSE,5398600645438
Apulki,342,1979,6,FALSE,5398600645438
Unpopular Essays,372,1950,2,FALSE,1834970381436
Deceiver,953,2019,2,FALSE,1220374157565
Veil: Secret Wars of the CIA,824,1991,6,FALSE,4711377519894
Char Shabda,544,1979,6,FALSE,7618040285496
Char Shabda,544,1979,2,FALSE,7618040285496
Rosy is My Relative,955,1993,2,FALSE,4826464866256
Moon and Sixpence,573,1973,5,FALSE,1142011562906
Moon and Sixpence,573,1973,1,FALSE,1142011562906
Political Philosophers,111,1970,4,FALSE,8913656935197
Short History of the World,618,1979,2,FALSE,7022242567424
Trembling of a Leaf,357,1952,5,FALSE,4213306202938
Doctor on the Brain,842,1982,6,FALSE,6088534854138
Doctor on the Brain,842,1982,4,FALSE,6088534854138
Simpsons & Their Mathematical Secrets,979,1968,3,FALSE,1841297655667
Pattern Classification,576,2009,6,FALSE,5324672445659
Pattern Classification,576,2009,2,FALSE,5324672445659
Pattern Classification,576,2009,2,FALSE,5324672445659
From Beirut to Jerusalem,486,1995,3,FALSE,5989553905396
From Beirut to Jerusalem,486,1995,2,FALSE,5989553905396
From Beirut to Jerusalem,486,1995,2,FALSE,5989553905396
Code Book,626,2005,5,FALSE,7352907992821
Code Book,626,2005,4,FALSE,7352907992821
Age of the Warrior,425,1963,5,FALSE,1377190001698
Final Crisis,106,1963,3,FALSE,2095586070159
Final Crisis,106,1963,1,FALSE,2095586070159
Final Crisis,106,1963,6,FALSE,2095586070159
Killing Joke,93,2006,6,FALSE,5977920028625
Killing Joke,93,2006,1,FALSE,5977920028625
Killing Joke,93,2006,1,FALSE,5977920028625
Flashpoint,185,1980,2,FALSE,9061067802958
Flashpoint,185,1980,1,FALSE,9061067802958
Batman Earth One,983,1956,3,FALSE,6672255640339
Crisis on Infinite Earths,378,1999,3,FALSE,5993113177685
Crisis on Infinite Earths,378,1999,5,FALSE,5993113177685
Numbers Behind Numb3rs,69,2000,1,FALSE,1889102642212
Numbers Behind Numb3rs,69,2000,3,FALSE,1889102642212
Numbers Behind Numb3rs,69,2000,2,FALSE,1889102642212
Superman Earth One - 1,83,1958,2,FALSE,2833848906793
Superman Earth One - 1,83,1958,4,FALSE,2833848906793
Superman Earth One - 1,83,1958,4,FALSE,2833848906793
Superman Earth One - 2,284,2005,4,FALSE,6468612458272
Justice League: Throne of Atlantis,148,2005,5,FALSE,6432529910157
Justice League: Throne of Atlantis,148,2005,1,FALSE,6432529910157
Justice League: Throne of Atlantis,148,2005,5,FALSE,6432529910157
Justice League: The Villain's Journey,547,2017,4,FALSE,8080652313013
Death of Superman,602,1974,6,FALSE,5154951597794
History of the DC Universe,80,2021,3,FALSE,5784984591164
Batman: The Long Halloween,84,2021,1,FALSE,4403731040016
Batman: The Long Halloween,84,2021,2,FALSE,4403731040016
Life in Letters,198,1994,4,FALSE,5583562930921
Life in Letters,198,1994,1,FALSE,5583562930921
Information,797,1995,5,FALSE,6870978203177
Journal of Economics,773,1983,4,FALSE,2389611849993
Elements of Information Theory,622,1986,1,FALSE,7155083198293
Power Electronics - Rashid,812,2011,5,FALSE,9287270251438
Power Electronics - Rashid,812,2011,6,FALSE,9287270251438
Power Electronics - Rashid,812,2011,2,FALSE,9287270251438
Power Electronics - Mohan,301,1984,6,FALSE,6420720877397
Power Electronics - Mohan,301,1984,6,FALSE,6420720877397
Neural Networks,410,1977,3,FALSE,7104150330157
Neural Networks,410,1977,1,FALSE,7104150330157
Grapes of Wrath,736,2003,6,FALSE,1605283259766
Vyakti ani Valli,467,1968,5,FALSE,6929434373089
Statistical Learning Theory,182,1976,2,FALSE,4834685608471
Empire of the Mughal - The Tainted Throne,868,2009,2,FALSE,7519339272212
Empire of the Mughal - The Tainted Throne,868,2009,1,FALSE,7519339272212
Empire of the Mughal - The Tainted Throne,868,2009,3,FALSE,7519339272212
Empire of the Mughal - Brothers at War,990,1976,5,FALSE,3173024130587
Empire of the Mughal - Ruler of the World,1000,2019,1,FALSE,5353783371718
Empire of the Mughal - The Serpent's Tooth,134,1983,4,FALSE,1605542887304
Empire of the Mughal - The Serpent's Tooth,134,1983,5,FALSE,1605542887304
Empire of the Mughal - The Serpent's Tooth,134,1983,2,FALSE,1605542887304
Empire of the Mughal - Raiders from the North,354,1963,3,FALSE,6247838291285
Empire of the Mughal - Raiders from the North,354,1963,6,FALSE,6247838291285
Mossad,748,2003,3,FALSE,2573567174454
Jim Corbett Omnibus,755,1987,4,FALSE,6036047966982
Jim Corbett Omnibus,755,1987,5,FALSE,6036047966982
20000 Leagues Under the Sea,581,1950,5,FALSE,9145332299087
Batatyachi Chal,181,1987,1,FALSE,1986485230310
Hafasavnuk,391,1980,6,FALSE,5387049947869
Hafasavnuk,391,1980,1,FALSE,5387049947869
Urlasurla,422,2019,2,FALSE,4820905396349
Pointers in C,128,1992,6,FALSE,2503298413813
Pointers in C,128,1992,5,FALSE,2503298413813
Cathedral and the Bazaar,929,1975,6,FALSE,6425172543802
Cathedral and the Bazaar,929,1975,1,FALSE,6425172543802
Cathedral and the Bazaar,929,1975,3,FALSE,6425172543802
Design with OpAmps,692,2013,2,FALSE,1475346594805
Design with OpAmps,692,2013,3,FALSE,1475346594805
Design with OpAmps,692,2013,6,FALSE,1475346594805
Think Complexity,659,1996,1,FALSE,8082399321646
Devil's Advocate,161,1996,4,FALSE,9662038681002
Ayn Rand Answers,744,2003,2,FALSE,2157101679675
Ayn Rand Answers,744,2003,6,FALSE,2157101679675
Ayn Rand Answers,744,2003,5,FALSE,2157101679675
Philosophy: Who Needs It,336,1973,5,FALSE,8217473778060
Philosophy: Who Needs It,336,1973,3,FALSE,8217473778060
World's Great Thinkers,720,2011,5,FALSE,8102727685154
World's Great Thinkers,720,2011,1,FALSE,8102727685154
World's Great Thinkers,720,2011,6,FALSE,8102727685154
Data Analysis with Open Source Tools,533,1966,6,FALSE,6244577727913
Data Analysis with Open Source Tools,533,1966,5,FALSE,6244577727913
Data Analysis with Open Source Tools,533,1966,5,FALSE,6244577727913
Broca's Brain,420,1991,3,FALSE,6859567928106
Broca's Brain,420,1991,5,FALSE,6859567928106
Broca's Brain,420,1991,1,FALSE,6859567928106
Men of Mathematics,758,1962,4,FALSE,9322557293759
Men of Mathematics,758,1962,2,FALSE,9322557293759
Oxford book of Modern Science Writing,391,1957,3,FALSE,4587042141771
Justice,357,1999,5,FALSE,8769930063792
Justice,357,1999,5,FALSE,8769930063792
Justice,357,1999,1,FALSE,8769930063792
Arthashastra,418,1961,6,FALSE,1504055530359
We the People,112,1987,3,FALSE,7926660584089
We the Nation,419,2017,1,FALSE,7779380086159
We the Nation,419,2017,4,FALSE,7779380086159
We the Nation,419,2017,2,FALSE,7779380086159
Courtroom Genius,856,1981,3,FALSE,9351977235124
Courtroom Genius,856,1981,5,FALSE,9351977235124
Dongri to Dubai,80,1957,2,FALSE,3729009781847
Dongri to Dubai,80,1957,4,FALSE,3729009781847
Dongri to Dubai,80,1957,2,FALSE,3729009781847
History of England,440,1990,2,FALSE,3512477645706
History of England,440,1990,4,FALSE,3512477645706
History of England,440,1990,5,FALSE,3512477645706
City of Djinns,691,2003,4,FALSE,5960021670772
India's Legal System,174,2004,4,FALSE,9850208666504
India's Legal System,174,2004,4,FALSE,9850208666504
India's Legal System,174,2004,6,FALSE,9850208666504
More Tears to Cry,806,1992,2,FALSE,8898125342722
Ropemaker,971,2013,5,FALSE,4042130121521
Ropemaker,971,2013,6,FALSE,4042130121521
Angels & Demons,936,1966,1,FALSE,7277026603041
Angels & Demons,936,1966,2,FALSE,7277026603041
Judge,900,1977,4,FALSE,6946886196974
Judge,900,1977,2,FALSE,6946886196974
Judge,900,1977,3,FALSE,6946886196974
Attorney,310,1973,1,FALSE,6131125722752
Prince,979,1985,4,FALSE,2901442747642
Prince,979,1985,5,FALSE,2901442747642
Prince,979,1985,5,FALSE,2901442747642
Eyeless in Gaza,707,2016,4,FALSE,3148304419043
Tales of Beedle the Bard,127,1982,6,FALSE,7908875865592
Tales of Beedle the Bard,127,1982,2,FALSE,7908875865592
Tales of Beedle the Bard,127,1982,5,FALSE,7908875865592
Girl with the Dragon Tattoo,703,2000,4,FALSE,2062995927060
Girl who kicked the Hornet's Nest,634,1955,3,FALSE,3615824837496
Girl who played with Fire,61,2006,3,FALSE,5781139318524
Girl who played with Fire,61,2006,5,FALSE,5781139318524
Batman Handbook,74,1957,4,FALSE,6297042402280
Murphy's Law,397,1955,5,FALSE,2620700611966
Murphy's Law,397,1955,4,FALSE,2620700611966
Murphy's Law,397,1955,3,FALSE,2620700611966
Structure and Randomness,876,2012,4,FALSE,4716387886019
Structure and Randomness,876,2012,4,FALSE,4716387886019
Image Processing with MATLAB,81,2018,1,FALSE,4575790962913
Image Processing with MATLAB,81,2018,6,FALSE,4575790962913
Animal Farm,267,1991,5,FALSE,6254174487442
Animal Farm,267,1991,3,FALSE,6254174487442
Animal Farm,267,1991,6,FALSE,6254174487442
Idiot,852,2022,3,FALSE,5275234842120
Idiot,852,2022,2,FALSE,5275234842120
Christmas Carol,910,1956,2,FALSE,5160623382231
Christmas Carol,910,1956,2,FALSE,5160623382231
\.

COPY autorzy (imie, nazwisko, data_urodzenia, notka_biograficzna) FROM stdin (Delimiter',');
Jaideva,Goswami,1811-8-1,\N
John,Foreman,1850-7-6,\N
Stephen,Hawking,1925-1-16,\N
Stephen,Dubner,1890-3-8,\N
Edward,Said,1936-6-21,\N
Vladimir,Vapnik,1928-10-15,\N
VP,Menon,1812-3-17,\N
Leonard,Mlodinow,1864-11-4,\N
Frank,Shih,1879-4-2,\N
Maria,Konnikova,1834-4-18,\N
Gutierrez,Sebastian,1894-10-28,\N
Kurt,Vonnegut,1806-8-1,\N
Cedric,Villani,1907-4-1,\N
Gerald,Sussman,1853-1-19,\N
Abraham,Eraly,1892-2-25,\N
Frank,Kafka,1922-6-17,\N
John,Pratt,1926-12-22,\N
Robert,Nisbet,1819-4-22,\N
H.G.,Wells,1818-6-4,\N
Werner,Heisenberg,1871-4-20,\N
Andy,Oram,1811-3-6,\N
Terence,Tao,1802-12-22,\N
Drew,Conway,1833-7-21,\N
Nate,Silver,1819-4-22,\N
Wes,McKinney,1806-2-16,\N
Thomas,Cormen,1914-4-21,\N
Siddhartha,Deb,1910-7-23,\N
Albert,Camus,1919-11-16,\N
ArthurConan,Doyle,1825-3-10,\N
Adam,Smith,1812-7-3,\N
Ken,Follett,1878-6-18,\N
Adolf,Hitler,1823-4-2,\N
Fritjof,Capra,1810-8-10,\N
Richard,Feynman,1903-3-13,\N
Ernest,Hemingway,1933-8-6,\N
Frederick,Forsyth,1920-11-6,\N
Jeffery,Archer,1856-11-19,\N
Randy,Pausch,1878-4-20,\N
Ayn,Rand,1931-12-7,\N
Michael,Crichton,1878-1-5,\N
John,Steinbeck,1905-10-7,\N
EdgarAllen,Poe,1824-2-28,\N
Will,Durant,1894-11-21,\N
PL,Deshpande,1807-12-7,\N
John,Grisham,1900-5-27,\N
V.S.,Naipaul,1876-12-20,\N
Joseph,Heller,1843-4-21,\N
\N,BBC,1801-1-20,\N
Bob,Dylan,1924-10-4,\N
Madan,Gupta,1904-9-21,\N
Alfred,Stonier,1891-8-26,\N
W.H.,Greene,1876-7-20,\N
Gary,Bradsky,1907-11-9,\N
Andrew,Tanenbaum,1805-12-6,\N
Schilling,Taub,1925-9-26,\N
Yashwant,Kanetkar,1938-6-23,\N
Jonathan,Stroud,1918-6-7,\N
Fyodor,Dostoevsky,1890-4-22,\N
Dan,Brown,1814-9-19,\N
Amartya,Sen,1800-7-3,\N
Amitav,Ghosh,1874-2-17,\N
Lorraine,Hansberry,1930-10-9,\N
Bob,Woodward,1801-9-2,\N
Kuldip,Nayar,1898-12-22,\N
William,Dalrymple,1927-10-5,\N
\N,Various,1820-10-17,\N
Sanjay,Garg,1814-11-6,\N
\N,,1825-6-18,\N
VP,Kale,1814-10-1,\N
Shashi,Tharoor,1834-12-4,\N
Dominique,Lapierre,1898-11-6,\N
Bertrand,Russell,1898-7-1,\N
Sam,Harris,1930-6-11,\N
EarleStanley,Gardner,1828-1-21,\N
Peter,Drucker,1868-6-5,\N
David,Bodanis,1836-9-12,\N
Victor,Hugo,1936-5-15,\N
Richard,Gordon,1839-9-5,\N
George,Orwell,1919-10-7,\N
Lee,Iacoca,1918-9-27,\N
WilliamS,Maugham,1894-7-16,\N
Robert,Pirsig,1802-5-20,\N
Robert,Fisk,1911-10-1,\N
Amir,Aczel,1828-11-15,\N
Samuel,Huntington,1861-8-14,\N
Richard,Bach,1816-5-5,\N
\N,Braithwaite,1857-4-3,\N
Jawaharlal,Nehru,1930-11-17,\N
Gerald,Durrell,1848-7-5,\N
Simon,Singh,1899-9-22,\N
Hart,Duda,1886-6-25,\N
Thomas,Friedman,1863-6-21,\N
Keith,Devlin,1806-9-21,\N
James,Gleick,1899-6-7,\N
Joy,Thomas,1895-5-13,\N
Muhammad,Rashid,1825-7-10,\N
Ned,Mohan,1880-11-6,\N
Simon,Haykin,1828-10-18,\N
Alex,Rutherford,1937-4-19,\N
Michael,Baz-Zohar,1856-10-3,\N
Jim,Corbett,1813-1-2,\N
Jules,Verne,1828-1-13,\N
\N,DeshpandePL,1860-4-2,\N
Eric,Raymond,1801-12-18,\N
Sergio,Franco,1881-6-27,\N
Allen,Downey,1843-1-28,\N
Morris,West,1817-6-19,\N
Phillip,Janert,1849-5-13,\N
Carl,Sagan,1833-11-28,\N
ET,Bell,1928-7-15,\N
Richard,Dawkins,1861-6-15,\N
Sudhanshu,Ranjan,1861-9-11,\N
\N,Kautiyla,1914-1-14,\N
\N,Palkhivala,1805-7-11,\N
\N,Sorabjee,1808-4-3,\N
Hussain,Zaidi,1905-12-1,\N
Peter,Ackroyd,1876-7-12,\N
\N,Nariman,1937-11-19,\N
Jean,Sassoon,1910-10-5,\N
Peter,Dickinson,1841-10-6,\N
\N,Machiavelli,1883-5-10,\N
Aldous,Huxley,1819-4-22,\N
JK,Rowling,1873-2-9,\N
Steig,Larsson,1812-11-1,\N
Steve,Eddins,1835-1-25,\N
Charles,Dickens,1818-5-21,\N
\.

COPY ksiazki_kategorie (unikalny_token, id_kategorii) FROM stdin (Delimiter',');
6729563152042,3
1014633866709,3
1014633866709,9
3166431008118,1
3979388223397,11
6150458423795,4
6150458423795,10
8751968732907,3
8751968732907,9
8410479003365,4
8410479003365,10
2070683790143,2
2070683790143,5
2070683790143,6
2070683790143,7
1503906609017,3
3310873923488,4
3310873923488,12
1573608583323,3
1573608583323,9
7847063688177,4
3821770068792,1
1103956323394,3
4988817066876,4
4988817066876,10
2395927307726,4
2445933217454,3
2445933217454,9
9061117269737,3
9061117269737,9
3276109300072,4
5534886439718,2
5534886439718,5
5534886439718,6
5534886439718,7
2715641095730,3
8194854910886,1
3337527420528,3
3337527420528,9
9874444732043,3
9874444732043,9
8438583493043,3
8438583493043,9
6666992569138,3
3703653195137,4
3703653195137,14
2408086432268,4
3864952503502,4
4950791696587,4
4457692192175,11
7041157546116,4
1196036295926,4
1196036295926,14
4984702655237,2
4984702655237,5
4984702655237,6
4984702655237,7
4077470030548,2
4077470030548,5
4077470030548,6
4077470030548,7
8890009561557,4
7312840521722,4
5670712431847,4
3806803489735,4
3806803489735,14
9529830388835,4
9529830388835,12
7591274432651,4
8940985935341,4
8940985935341,14
3295708841378,4
9519263308660,11
1813594418598,2
1813594418598,5
1813594418598,6
1813594418598,7
4769134534695,4
4769134534695,12
6557719081108,4
3318082805969,4
7756274497478,4
7756274497478,14
6131558292251,4
3445864921706,4
4525160406226,4
4565543007532,4
7572023417380,4
7572023417380,14
6043519184697,4
6043519184697,14
6840320046576,3
6840320046576,9
6754683435055,11
2935989317694,11
7178656973092,3
7178656973092,9
4489833524936,3
4107897544048,3
4107897544048,9
5025723308014,3
2940061686577,3
5154540150755,4
3196057839502,4
7092094079047,4
8271414721143,4
8271414721143,14
6895840887435,4
2104120929684,4
2104120929684,14
2868244317596,4
3336350705716,4
3336350705716,10
2824954837500,4
1786737440113,4
1786737440113,10
8200019656134,4
8200019656134,14
7779826332167,4
7779826332167,10
8321473552475,11
3425070305420,4
3425070305420,14
5180853337094,4
5180853337094,14
1735550908152,4
1735550908152,14
1001279279670,4
5714537331897,4
5714537331897,14
5897507298928,4
5897507298928,14
8945761395204,4
8945761395204,10
3402496073178,4
3402496073178,10
7485925923565,4
8416450607048,4
8416450607048,10
6170155389673,4
4187709059758,4
4187709059758,10
3016871132439,4
1203924092495,4
1203924092495,12
5050639084270,4
5050639084270,12
7544691406925,4
7544691406925,14
3123529631678,4
4464398397212,2
4464398397212,5
4464398397212,6
4464398397212,7
3637338181330,11
1064149956681,2
1064149956681,5
1064149956681,6
1064149956681,7
7585429115614,4
6479758169529,4
7214443729247,11
9546616317438,4
6257874156783,4
6257874156783,14
4065255404829,4
4065255404829,12
9488110719161,4
9488110719161,10
8465721830580,4
3513097276126,4
3513097276126,14
2477763455615,4
1574693943745,4
8605438025356,4
3127814260230,4
3127814260230,12
6163804811943,4
6163804811943,10
6494319505401,4
8038081819134,2
8038081819134,5
8038081819134,6
8038081819134,7
6347509939946,4
6347509939946,12
6172217379259,4
8468296521342,11
1435023114521,4
1435023114521,10
3362307658463,4
3362307658463,14
3864611194399,4
3864611194399,14
9573404173566,4
9573404173566,14
3186466186968,4
9266170429737,4
8002913475297,4
8002913475297,10
5398600645438,4
5398600645438,14
1834970381436,4
1834970381436,12
1220374157565,4
4711377519894,4
4711377519894,10
7618040285496,4
7618040285496,14
4826464866256,4
1142011562906,4
8913656935197,4
8913656935197,12
7022242567424,4
7022242567424,10
4213306202938,4
6088534854138,4
1841297655667,2
1841297655667,5
1841297655667,6
1841297655667,7
5324672445659,3
5324672445659,9
5989553905396,4
5989553905396,10
7352907992821,2
7352907992821,5
7352907992821,6
7352907992821,7
1377190001698,4
1377190001698,10
2095586070159,4
2095586070159,13
5977920028625,4
5977920028625,13
9061067802958,4
9061067802958,13
6672255640339,4
6672255640339,13
5993113177685,4
5993113177685,13
1889102642212,2
1889102642212,5
1889102642212,6
1889102642212,7
2833848906793,4
2833848906793,13
6468612458272,4
6468612458272,13
6432529910157,4
6432529910157,13
8080652313013,4
8080652313013,13
5154951597794,4
5154951597794,13
5784984591164,4
5784984591164,13
4403731040016,4
4403731040016,13
5583562930921,4
5583562930921,14
6870978203177,2
6870978203177,5
6870978203177,6
6870978203177,7
2389611849993,11
7155083198293,3
7155083198293,9
9287270251438,3
6420720877397,3
7104150330157,3
7104150330157,9
1605283259766,4
6929434373089,4
6929434373089,14
4834685608471,3
4834685608471,9
7519339272212,4
7519339272212,10
3173024130587,4
3173024130587,10
5353783371718,4
5353783371718,10
1605542887304,4
1605542887304,10
6247838291285,4
6247838291285,10
2573567174454,4
2573567174454,10
6036047966982,4
6036047966982,14
9145332299087,4
1986485230310,4
5387049947869,4
4820905396349,4
2503298413813,3
6425172543802,3
1475346594805,3
8082399321646,3
8082399321646,9
9662038681002,4
2157101679675,4
2157101679675,12
8217473778060,4
8217473778060,12
8102727685154,4
8102727685154,12
6244577727913,3
6244577727913,9
6859567928106,2
6859567928106,5
6859567928106,6
6859567928106,7
9322557293759,1
4587042141771,2
4587042141771,5
4587042141771,6
4587042141771,7
8769930063792,4
8769930063792,12
1504055530359,4
1504055530359,12
7926660584089,4
7926660584089,12
7779380086159,4
7779380086159,12
9351977235124,4
9351977235124,14
3729009781847,4
3729009781847,14
3512477645706,4
3512477645706,10
5960021670772,4
5960021670772,10
9850208666504,4
9850208666504,14
8898125342722,4
4042130121521,4
7277026603041,4
6946886196974,4
6131125722752,4
2901442747642,4
2901442747642,12
3148304419043,4
7908875865592,4
2062995927060,4
3615824837496,4
5781139318524,4
6297042402280,4
6297042402280,13
2620700611966,4
2620700611966,14
4716387886019,1
4575790962913,3
6254174487442,4
5275234842120,4
5160623382231,4
\.

COPY ksiazki_autorzy (unikalny_token, id_autora) FROM stdin (Delimiter',');
6729563152042,1
1014633866709,2
3166431008118,3
3979388223397,4
6150458423795,5
8751968732907,6
8410479003365,7
2070683790143,8
1503906609017,9
3310873923488,10
1573608583323,11
7847063688177,12
3821770068792,13
1103956323394,14
4988817066876,15
2395927307726,16
2445933217454,17
9061117269737,18
3276109300072,19
5534886439718,20
2715641095730,21
8194854910886,22
3337527420528,23
9874444732043,24
8438583493043,25
6666992569138,26
3703653195137,27
2408086432268,28
3864952503502,29
4950791696587,29
4457692192175,30
7041157546116,31
1196036295926,32
4984702655237,33
4077470030548,34
8890009561557,35
7312840521722,36
5670712431847,37
3806803489735,38
9529830388835,39
7591274432651,40
8940985935341,41
3295708841378,42
9519263308660,4
1813594418598,33
4769134534695,43
6557719081108,44
3318082805969,41
7756274497478,41
6131558292251,41
3445864921706,45
4525160406226,46
4565543007532,47
7572023417380,48
6043519184697,49
6840320046576,50
6754683435055,51
2935989317694,52
7178656973092,53
4489833524936,54
4107897544048,36
5025723308014,55
2940061686577,56
5154540150755,57
3196057839502,58
7092094079047,59
8271414721143,60
6895840887435,61
2104120929684,60
2868244317596,62
3336350705716,63
2824954837500,37
1786737440113,64
8200019656134,44
7779826332167,65
8321473552475,66
3425070305420,44
5180853337094,44
1735550908152,44
1001279279670,67
5714537331897,68
5897507298928,69
8945761395204,70
3402496073178,68
7485925923565,70
8416450607048,71
6170155389673,71
4187709059758,71
3016871132439,41
1203924092495,72
5050639084270,73
7544691406925,70
3123529631678,74
4464398397212,3
3637338181330,75
1064149956681,76
7585429115614,77
6479758169529,41
7214443729247,75
9546616317438,78
6257874156783,79
4065255404829,60
9488110719161,65
8465721830580,68
3513097276126,80
2477763455615,81
1574693943745,36
8605438025356,81
3127814260230,82
6163804811943,83
6494319505401,39
8038081819134,84
6347509939946,72
6172217379259,68
8468296521342,60
1435023114521,85
3362307658463,33
3864611194399,86
9573404173566,68
3186466186968,87
9266170429737,46
8002913475297,88
5398600645438,44
1834970381436,72
1220374157565,36
4711377519894,63
7618040285496,44
4826464866256,89
1142011562906,81
8913656935197,68
7022242567424,19
4213306202938,81
6088534854138,78
1841297655667,90
5324672445659,91
5989553905396,92
7352907992821,90
1377190001698,83
2095586070159,68
5977920028625,68
9061067802958,68
6672255640339,68
5993113177685,68
1889102642212,93
2833848906793,68
6468612458272,68
6432529910157,68
8080652313013,68
5154951597794,68
5784984591164,68
4403731040016,68
5583562930921,41
6870978203177,94
2389611849993,68
7155083198293,95
9287270251438,96
6420720877397,97
7104150330157,98
1605283259766,41
6929434373089,44
4834685608471,6
7519339272212,99
3173024130587,99
5353783371718,99
1605542887304,99
6247838291285,99
2573567174454,100
6036047966982,101
9145332299087,102
1986485230310,103
5387049947869,103
4820905396349,103
2503298413813,56
6425172543802,104
1475346594805,105
8082399321646,106
9662038681002,107
2157101679675,39
8217473778060,39
8102727685154,68
6244577727913,108
6859567928106,109
9322557293759,110
4587042141771,111
8769930063792,112
1504055530359,113
7926660584089,114
7779380086159,114
9351977235124,115
3729009781847,116
3512477645706,117
5960021670772,65
9850208666504,118
8898125342722,119
4042130121521,120
7277026603041,59
6946886196974,68
6131125722752,68
2901442747642,121
3148304419043,122
7908875865592,123
2062995927060,124
3615824837496,124
5781139318524,124
6297042402280,68
2620700611966,68
4716387886019,22
4575790962913,125
6254174487442,79
5275234842120,58
5160623382231,126
\.

COPY studenci (imie, nazwisko, nazwa_uzytkownika) FROM stdin (Delimiter',');
Ariel,Gąsowski,AriGą
Fabian,Gajos,FabGaj
Teodora,Bany,TeoBan
Agnieszka,Frelich,AgnFre
Lucjan,Janicki,LucJan
Janina,Mądrzyk,JanMą
Berenika,Antończak,BerAnt
Sebastian,Gomułka,SebGom
Bogna,Sobaszek,BogSob
Wera,Kloska,WerKlo
Justyn,Kałuski,JusKa�
Zuzanna,Brylińska,ZuzBry
Jonatan,Igielski,JonIgi
Metody,Czarkowski,MetCza
Rajmund,Pol,RajPol
Dargomira,Sot,DarSot
Delia,Działowska,DelDzi
Hiacynta,Uss,HiaUss
Świetlana,Mańska,ŚwMa�
Roberta,Dułak,RobDu�
Ożanna,Domitrz,OżDom
Walery,Kuźmicki,WalKu�
Ada,Zawacka,AdaZaw
Ładana,Tarnacka,ŁaTar
\.

COPY hasla_studentow (id_studenta, haslo_hash_s) FROM stdin (Delimiter',');
1,QSaWRBiZuht!ATVnKNCCnNAdplU&AZrXGeBmsw#ThDujB@!jJni#tydJehLshlNT
2,T*o#@%i^xlAzgg^YDpuUOLCjAX!LQySrsHXblcVm%sTDVPymHWRFEgEEipYpppps
3,bwB#kRUKIUhegIkD@BsXSJeLO&ffkOP*tUSyDHcFscTtyzMhe^q!MpiQ@wj#Bd@O
4,S!vlGEEHgiDHJw@voIUnCFRntFFB*RTrb&UZ$NxSWkRUeuQ%$HRxRydxkTpgWLgN
5,!IU^hq@sYzF#!i#RB!OFzVm*#FO^S@YHZLoG#vdloHqIzwGsQHP*xpMYNZZqjhfF
6,qAYL^&nTg#sj^oPb%XjrTxxRDZNXXpQIDFygaoTQ%F#*gqz^nGHHGo&UCe@wsbg%
7,bQlD%lesdzOecl$j@IGfUnPpKrOtIqzOya@s$RPNQmhDSmqHnttFXertsSfYyzMt
8,fnZZx*#NJG!YyBdQJsPF$RfHSZivOSzx&Tek*YBbjXALf%v*uKxNgsPXixiNoHdt
9,AeTdsgfwa*QenJLXnHffnOhCaCnvsG%uPnjmYjybWvBIVWCcCDEbtMPXUw@oOGBn
10,dnTtEupkvyAeFcwGdpIzoux%!bwE!kzUf%OJ&ZoTqiJiDwcszzlZnEoMemazUYDV
11,b#NbnQNJNH@DMm%zAfEci%^QTqK%&yezKFgWbCdttkzye!YKTuspBLIGZfD#GCgd
12,s&CGI*Tvm^ktOHHNug@GoskO&xuZbjEPWvH@MvR&tWvj$riNk*xe@G$hfITqNLem
13,SEhmE$njcunMZMrwpQ@KWO^S#jVym#MlakWKcTqMljhJ#zaxFj$ECXGGLf$tgPvg
14,ICuk&IqAmpltk#s$s&WHlcc&%AmUlHmsao%KhaKSpjagHytyLQXPUkMwi%FO^SuQ
15,Dgl!pHH!ZG&jfTAHYyHdUQY%rt$nASiEbrAcqwMdmnRtKdFwcsHITktTSIzgfkMp
16,RpHCiVymkTSyLVaCYoyQLICSJxn&ogkBP!RyfCw*SFOS!DxsKXViroXzpGAnz%nz
17,oifI@qv%iErS^z%%TRIdqXun^&zp@GpEwAgSgz@CI^BJWMmR#eqRamExxbrPOHRC
18,TJdqJPTQaHZkn&Is#ebP%JkdZGFcgGgkSFhPWP#V*&Dqux!DaUFdOEwoiHMxfgqu
19,LQ*ef!hrRGqLToJPsO*qaX#FIAhJkiNlfShqYOD*WJuDW#HrpSqDmZRoqKDQDXs#
20,OKcfBVdkNgVnIzIzpYKiG@bhOpvuF!VQ*BD*WBUmU&IGj^z^QOlaCOZ*PAxMQ%hv
21,!o*N^kYaNZmMYe$UeTc&eLs@t$slJAjH@AHa&OAMirV!&Kyl^yTOiVPMAGlRRQ@I
22,mIYlxd#F$CN@ZMFX@YBuXjDLYILtXGL#tfR&nHCr#Rn@dXKZWVSE^MUEazPQCltR
23,LYq*c%PhJWfbPNTfchc%bVhzU@oqEbhKU&CM%wewvHMmTIpJ!DVG&%ipHrLoYWAI
24,nbxnXa#O!pLcIJuUWlVgdrlZA&QYuHy%!Nl#RH&auHHegQuj$xF%No^f*OO$RROk
\.

COPY pracownicy (imie, nazwisko, nazwa_uzytkownika, id_etatu, email, telefon, id_oddzialu) FROM stdin (Delimiter',');
Robert,Marczuk,RobMar,4,Robert.Marczuk@interia.pl,\N,1
Paweł,Bucki,PawBuc,1,Paweł.Bucki@interia.pl,\N,6
Eryka,Jałowiec,EryJa�,1,Ernest.Rak@gmail.com,\N,5
Rudolfina,Ulicka,RudUli,1,Sergiusz.Krzysztofik@wp.pl,\N,5
Tessa,Sot,TesSot,1,Walid.Orlikowski@gmail.com,\N,6
Świętopełk,Ptaszek,ŚwPta,3,Świętopełk.Ptaszek@gmail.com,\N,2
Macieja,Wacław,MacWac,2,Manfred.Pokora@epic.games,\N,1
Wincenty,Fila,WinFil,6,Wincenty.Fila@epic.games,\N,4
Daniel,Romaniuk,DanRom,6,Daniel.Romaniuk@tcs.uj,\N,6
Bert,Świdziński,BerŚw,3,Bert.Świdziński@tcs.uj,\N,3
Iga,Dycha,IgaDyc,3,Ignacy.Prokop@lambda.calc,\N,5
Chociemir,Krupka,ChoKru,5,Chociemir.Krupka@tcs.uj,\N,1
Ildefonsa,Jastrząbek,IldJas,3,Igor.Ołdak@tcs.uj,\N,6
Kira,Głąbicka,KirGł,5,Klemens.Berger@gmail.com,\N,3
postgres,postgres,postgres,\N,postgres,\N,\N
\.

COPY hasla_pracownikow (id_pracownika, haslo_hash_p) FROM stdin (Delimiter',');
1,m!Qa&&cIuHSbmrQgX#CVChKSVJETuFojFk!nlE$eodUrUTJkMzWG#*AwchWITrXs
2,%*rSiXL%c#jPAwooYU^Iu%s&jBthhXNNPNcRLqiBtYI@SQCsIsqrAesH@OGl$oB!
3,DEpnt%J*fxTt^Jnp!TFAKaIgN&s$&roUKphRuMhl!%DrVoyOwZE!QyxTvnoP#M!a
4,YdcprbhaitFRSl&bdSfOvpb*vHKhTHCRFkwWMSS%v&UJAsgNQmdWBdJx#vJCwwkz
5,OyC&%MwsdvhBJETSr#GYHAUjxd!XWah@NXZEXCGIdoMdcvw*Vdvg%HXwc^#@jDJe
6,PLiBdEMH$SsvFHcrKpU&sKzfYiwKyhPCpxQzmaocywtRftn%xgQGbpf&NlZJXR&G
7,JiJ^Ek^XtXYaAVgJ#RIOSvEPPqkXKyXKFihgmFMtQrlbXOsp!GH!&yuxqvcM^qNL
8,n$xqXeUNtgLnomqVote#TMEtyqikGnaMRzphhbufr*D!@DDlUjsbGuHEDMKYDiFd
9,pPEGjcgwN&kA*iW$Dw%sFzOVSQDDGnTOdCjd*RivNzrWMnQCFzsSoBOMZ$GG@iLU
10,Awx&bFpwq@ELx!c@XCd*fyKF*q%bK@%vWNfBxRN#cAiLIOPwP@%VOoHV^N&g&xnp
11,HJJHzex*bphvyIFSafKzBBRDlQXJfBXEjfi!BZOSX&mS$IxEJaOepVrrJ^MctPxz
12,up%ncFPUQzlkjqsuv&lTIuJaFE@b&HiLwpy$GF$NC@VCmKFF@A#wHKZbnWfSKlii
13,t&apYkAUt#ffAI$#DsSHPfESiIArKIA%NphhbT^FiifP#L@LeOYIi^dryHLMHVxX
14,FOwzx!WNH#QLiAIrQ^qZSDdH%rowfosHzJz^gJLrxIu!xjwKEnjsRqbi&s%kZFGA
\.

COPY studenci_kierunki (id_studenta, id_kierunku, start, koniec) FROM stdin (Delimiter',');
1,6,2014-10-01,2017-09-30
1,7,2010-10-01,2013-09-30
2,13,2011-10-01,2014-09-30
3,5,2019-10-01,2022-09-30
4,2,2022-10-01,2025-09-30
5,1,2019-10-01,2022-09-30
6,2,2011-10-01,2014-09-30
6,3,2013-10-01,2016-09-30
7,6,2022-10-01,2025-09-30
8,15,2012-10-01,2015-09-30
9,14,2013-10-01,2016-09-30
9,15,2022-10-01,2025-09-30
10,13,2016-10-01,2019-09-30
10,14,2016-10-01,2019-09-30
11,15,2016-10-01,2019-09-30
12,6,2018-10-01,2021-09-30
12,7,2023-10-01,2026-09-30
13,17,2021-10-01,2024-09-30
13,1,2016-10-01,2019-09-30
14,1,2021-10-01,2024-09-30
15,17,2010-10-01,2013-09-30
15,1,2010-10-01,2013-09-30
16,13,2011-10-01,2014-09-30
16,14,2016-10-01,2019-09-30
17,8,2021-10-01,2024-09-30
17,9,2023-10-01,2026-09-30
18,10,2021-10-01,2024-09-30
18,11,2013-10-01,2016-09-30
19,3,2022-10-01,2025-09-30
19,4,2017-10-01,2020-09-30
20,5,2019-10-01,2022-09-30
20,6,2011-10-01,2014-09-30
21,15,2015-10-01,2018-09-30
21,16,2015-10-01,2018-09-30
22,6,2021-10-01,2024-09-30
22,7,2019-10-01,2022-09-30
23,1,2013-10-01,2016-09-30
23,2,2020-10-01,2023-09-30
24,4,2013-10-01,2016-09-30
\.

COPY wypozyczenia (id_studenta, id_pracownika, id_ksiazki, data_wypozyczenia, termin_oddania) FROM stdin (Delimiter',');
1,15,1,\N,\N
2,15,2,\N,\N
3,15,3,\N,\N
4,15,4,\N,\N
5,15,5,\N,\N
6,15,6,\N,\N
7,15,7,\N,\N
8,15,8,\N,\N
9,15,9,\N,\N
10,15,10,\N,\N
11,15,11,\N,\N
12,15,12,\N,\N
13,15,13,\N,\N
14,15,14,\N,\N
15,15,15,\N,\N
16,15,16,\N,\N
17,15,17,\N,\N
18,15,18,\N,\N
19,15,19,\N,\N
20,15,20,\N,\N
21,15,21,\N,\N
22,15,22,\N,\N
23,15,23,\N,\N
24,15,24,\N,\N
\.

COPY zwroty (id_wypozyczenia, id_oddzialu, id_pracownika, data_zwrotu) FROM stdin (Delimiter',');
1,1,15,2023-06-26
2,1,15,2023-06-27
3,2,15,2023-06-27
4,1,15,2023-06-23
5,2,15,2023-06-23
6,6,15,2023-06-24
\.




--------------------------------------------------------------------------------------------------------





-- widze ze przyda sie widok wypozyczenia zwroty
create or replace view wypozyczenia_zwroty as (
    select w.*, z.id_oddzialu as "id_oddzialu_zwrot", z.id_pracownika as "id_pracownika_zwrot", z.data_zwrotu, z.id_zwrotu from wypozyczenia w left join zwroty z on w.id_wypozyczenia = z.id_wypozyczenia
);

-- 2 przydatne widoki
create or replace view ksiazki_autorzy_v as (
    select k.unikalny_token, k.tytul, k.rok_wydania, array_agg(distinct a.id_autora) as "id autora", array_agg(distinct a.nazwisko) as "nazwisko" 
    from ksiazki k 
    left join ksiazki_autorzy ka on k.unikalny_token = ka.unikalny_token
    left join autorzy a on a.id_autora = ka.id_autora
    group by (k.unikalny_token, k.tytul, k.liczba_stron, k.rok_wydania)
);

create or replace view ksiazki_kategorie_v as (
    select k.unikalny_token, k.tytul, k.rok_wydania, array_agg(distinct kat.id_kategorii) as "id kat", array_agg(distinct kat.nazwa) as "nazwa" 
    from ksiazki k 
    left join ksiazki_kategorie kk on k.unikalny_token = kk.unikalny_token
    left join kategorie kat on kat.id_kategorii = kk.id_kategorii
    group by (k.unikalny_token, k.tytul, k.liczba_stron, k.rok_wydania)
);
